nginx:
    build: docker/nginx
    restart: always
    links:
        - front
        - transformer
    volumes_from:
        - images_data
        - logs_data
        - nginx_cache
transformer:
    image: transformer
    restart: always
    volumes_from:
        - images_data
front:
    image: lazyants/filecessor-front
    restart: always
    volumes_from:
        - images_data
        - logs_data
    links:
        - db
        - rabbit
handler:
    image: lazyants/filecessor-handler
    restart: always
    volumes_from:
        - images_data
        - logs_data
    links:
        - db
        - rabbit
db:
    image: umputun/mongo-auth
    restart: always
    volumes_from:
        - db_data
    environment:
        MONGO_PASSWD: app
rabbit:
    image: rabbitmq:3
    restart: always
    volumes_from:
        - db_data

#data containers
images_data:
    image: debian:jessie
    volumes:
        - /var/tmp/uploads
        - /var/cache/uploads
        - ./media:/media
    tty: true
nginx_cache:
    image: debian:jessie
    volumes:
        - /var/cache/nginx
    tty: true
db_data:
    image: debian:jessie
    volumes:
        - /data/db
        - /var/lib/rabbitmq
    tty: true
logs_data:
    image: debian:jessie
    volumes:
        - /var/log/nginx
        - /var/log/filecessor
    tty: true
